import { Injectable } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { Observable } from 'rxjs';

const API_URL = 'https://binaried-5dmm.onrender.com/api/tasks';
const AI_URL = 'https://binaried-5dmm.onrender.com/api/ai';

export interface Task {
  _id?: string;
  title: string;
  description?: string;
  status: 'todo' | 'in-progress' | 'done';
  priority: 'low' | 'medium' | 'high';
  tags?: string[];
  dueDate?: string | null;
  createdAt?: string;
}

export interface TaskFilters {
  status?: string;
  priority?: string;
  search?: string;
}

export interface AiSuggestion {
  description: string;
  subtasks: string[];
}

// Thin wrapper around the /api/tasks endpoints. The JWT token is attached
// automatically by auth.interceptor.ts, so this service doesn't need to
// worry about headers at all.
@Injectable({ providedIn: 'root' })
export class TaskService {
  constructor(private http: HttpClient) {}

  getTasks(filters: TaskFilters = {}): Observable<Task[]> {
    let params = new HttpParams();
    if (filters.status) params = params.set('status', filters.status);
    if (filters.priority) params = params.set('priority', filters.priority);
    if (filters.search) params = params.set('search', filters.search);

    return this.http.get<Task[]>(API_URL, { params });
  }

  // Calls the AI-powered suggestion endpoint: given a title, returns a
  // short description and a few subtasks generated by Claude.
  getAiSuggestion(title: string): Observable<AiSuggestion> {
    return this.http.post<AiSuggestion>(`${AI_URL}/suggest`, { title });
  }

  createTask(task: Partial<Task>): Observable<Task> {
    return this.http.post<Task>(API_URL, task);
  }

  updateTask(id: string, task: Partial<Task>): Observable<Task> {
    return this.http.put<Task>(`${API_URL}/${id}`, task);
  }

  deleteTask(id: string): Observable<{ message: string }> {
    return this.http.delete<{ message: string }>(`${API_URL}/${id}`);
  }
}
